### ISSUE TITLE
maintainer rights

### ISSUE THREAD

**Issue by sappelhoff** [conda-forge/pybv-feedstock#2]
@hoechenberger can you add me as a maintainer here, please?

It'll reduce the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) and may help me to familiarize myself a bit better with conda forge :-)

**Comment by hoechenberger** [comment]
No problem, just create a PR where you add yourself to the maintainers section of the recipe, and then follow the instructions to re-render. Once CI passes, I can merge. 

Ping me if you need help
